import java.util.Scanner;

public class Exception
{
    public static void main(String args[])
    {
        Scanner sc =new Scanner (System.in);
        try
        {
           System.out.println("enter the first number ");
           int a = sc.nextInt();
           System.out.println("enter the second number");
           int b= sc.nextInt();
           int c = a/b;
           System.out.println("Result is :"+c);
        }
        catch(ArithmeticException e)
        {
           System.out.println(e.getMessage());
        }
        finally
        {
            System.out.println("end of operation");
        }
    }
}
